import { useEffect, useMemo, useState } from 'react';
import type { ReactElement } from 'react';
import {
  advanceNationKernelDays, assignProductionFactories, conductMissileDemonstration, createGlobalUnificationPlaytestState,
  createIndustrialStrategy, globalUnificationReadiness, launchBasicSatellite, ratifyGlobalSettlement, resolveStrategicEvent,
  setCooperationContribution, setEconomicAllocation, setIndustrialStrategy, setOccupationApproach, setPoliticalIdentity,
  startCivilizationTechnology, startCooperationProject, startNationalDevelopmentProject, activateCivilizationPolicy, strategicAssetPresentation, strategicDirectionOptions, selectStrategicDirection, strategicBoardObjects,
} from '../nationKernel';
import type { AuthorityModel, NationKernelState } from '../nationKernel';
import './strategicCabinet.css';

type CategoryId = 'nation'|'politics'|'society'|'events'|'research'|'economy'|'construction'|'industry'|'equipment'|'logistics'|'regions'|'diplomacy'|'intelligence'|'military'|'army'|'navy'|'air'|'space'|'war'|'global'|'archive';
type Category = { id: CategoryId; icon: string; label: string; tabs: Array<{ id: string; label: string }> };
const categories: Category[] = ([
  { id:'nation',icon:'⌂',label:'国家',tabs:[{id:'overview',label:'国家总览'},{id:'identity',label:'政体'},{id:'ethics',label:'文明理念'},{id:'route',label:'国家路线'},{id:'spirits',label:'国家精神'}]},
  { id:'politics',icon:'♜',label:'政治',tabs:[{id:'domestic',label:'国内政治'},{id:'factions',label:'政治派系'},{id:'cabinet',label:'政府与内阁'},{id:'laws',label:'法律'},{id:'policies',label:'政策与法令'}]},
  { id:'society',icon:'◉',label:'社会',tabs:[{id:'population',label:'人口'},{id:'groups',label:'社会集团'},{id:'living',label:'生活状况'},{id:'culture',label:'文化'},{id:'education',label:'教育'}]},
  { id:'events',icon:'!',label:'事件与局势',tabs:[{id:'event-list',label:'事件'},{id:'situations',label:'局势'},{id:'missions',label:'国家任务'},{id:'reports',label:'报告'}]},
  { id:'research',icon:'⌬',label:'科研',tabs:[{id:'technology',label:'科技树'},{id:'current',label:'当前研究'},{id:'special',label:'特殊项目'},{id:'institutes',label:'科研机构'},{id:'tech-archive',label:'科技档案'}]},
  { id:'economy',icon:'◇',label:'经济',tabs:[{id:'economic-overview',label:'经济总览'},{id:'finance',label:'财政'},{id:'budget',label:'预算'},{id:'resources',label:'资源'},{id:'trade',label:'贸易'},{id:'market',label:'市场'}]},
  { id:'construction',icon:'▱',label:'建设',tabs:[{id:'queue',label:'建设队列'},{id:'projects',label:'国家工程'},{id:'urban',label:'城市建设'},{id:'infrastructure',label:'基础设施'},{id:'repair',label:'维护与修复'}]},
  { id:'industry',icon:'▦',label:'工业',tabs:[{id:'industrial-overview',label:'工业总览'},{id:'civilian',label:'民用工业'},{id:'military-industry',label:'军事工业'},{id:'shipbuilding',label:'造船工业'},{id:'organizations',label:'工业组织'},{id:'industrial-route',label:'工业路线'}]},
  { id:'equipment',icon:'◆',label:'装备',tabs:[{id:'design',label:'装备设计'},{id:'catalog',label:'装备目录'},{id:'strategic-assets',label:'战略资产'},{id:'stockpile',label:'库存'},{id:'equipment-maintenance',label:'装备维护'}]},
  { id:'logistics',icon:'⇄',label:'物流',tabs:[{id:'logistics-overview',label:'物流总览'},{id:'land-transport',label:'陆路运输'},{id:'shipping',label:'海运'},{id:'airlift',label:'空运'},{id:'reserves',label:'战略储备'},{id:'supply',label:'补给网络'}]},
  { id:'regions',icon:'◎',label:'地区',tabs:[{id:'region-overview',label:'地区总览'},{id:'cities',label:'城市'},{id:'administration',label:'地方行政'},{id:'services',label:'公共服务'},{id:'integration',label:'地区整合'},{id:'occupation',label:'占领管理'},{id:'reconstruction',label:'战后重建'}]},
  { id:'diplomacy',icon:'♢',label:'外交',tabs:[{id:'relations',label:'势力关系'},{id:'actions',label:'外交行动'},{id:'negotiation',label:'谈判'},{id:'alliances',label:'联盟'},{id:'cooperation',label:'国际合作'},{id:'international-orgs',label:'国际组织'},{id:'treaties',label:'协议档案'}]},
  { id:'intelligence',icon:'⌾',label:'情报',tabs:[{id:'intel-overview',label:'情报总览'},{id:'foreign-intel',label:'势力情报'},{id:'recon',label:'侦察网络'},{id:'covert',label:'秘密行动'},{id:'counterintel',label:'反间谍'}]},
  { id:'military',icon:'✥',label:'军事',tabs:[{id:'defense',label:'国防总览'},{id:'military-policy',label:'军事政策'},{id:'command',label:'军事指挥'},{id:'doctrine',label:'军事学说'},{id:'mobilization',label:'动员'}]},
  { id:'army',icon:'▰',label:'陆军',tabs:[{id:'army-formations',label:'陆军编制'},{id:'army-units',label:'部队'},{id:'army-deployment',label:'陆军部署'},{id:'army-training',label:'陆军训练'}]},
  { id:'navy',icon:'≈',label:'海军',tabs:[{id:'fleets',label:'舰队'},{id:'ship-design',label:'舰艇设计'},{id:'naval-deployment',label:'海军部署'},{id:'naval-repair',label:'港口与维修'}]},
  { id:'air',icon:'⌁',label:'空军与导弹',tabs:[{id:'air-overview',label:'空军总览'},{id:'aircraft-design',label:'飞机设计'},{id:'air-deployment',label:'空军部署'},{id:'airbases',label:'机场'},{id:'missiles',label:'导弹力量'}]},
  { id:'space',icon:'△',label:'航天',tabs:[{id:'space-program',label:'航天计划'},{id:'launches',label:'发射任务'},{id:'satellites',label:'卫星网络'},{id:'launch-sites',label:'发射场'},{id:'ground-stations',label:'地面站'},{id:'orbital',label:'轨道设施'},{id:'space-cooperation',label:'航天合作'}]},
  { id:'war',icon:'⚑',label:'战争',tabs:[{id:'war-overview',label:'战争总览'},{id:'theatres',label:'战区'},{id:'campaigns',label:'战役'},{id:'losses',label:'伤亡与损失'},{id:'ceasefire',label:'停火谈判'},{id:'peace',label:'和平会议'}]},
  { id:'global',icon:'✦',label:'全球共同体',tabs:[{id:'world-order',label:'全球秩序'},{id:'institutions',label:'共同机构'},{id:'resolutions',label:'全球议案'},{id:'public-projects',label:'全球公共项目'},{id:'members',label:'成员与义务'},{id:'unification',label:'全球统一进程'}]},
  { id:'archive',icon:'▤',label:'历史与档案',tabs:[{id:'chronicle',label:'编年史'},{id:'decisions',label:'重大决策'},{id:'archive-tech',label:'科技档案'},{id:'archive-projects',label:'工程档案'},{id:'archive-wars',label:'战争档案'},{id:'service-history',label:'装备服役史'}]},
] as Category[]).map(category=>({...category,tabs:[...category.tabs,{id:'direction-options',label:'方向对比'}]}));

const directionCatalog = strategicDirectionOptions();
const boardCatalog = strategicBoardObjects();
const directionMetricLabels: Array<[keyof ReturnType<typeof strategicDirectionOptions>[string]['metrics'],string,boolean]> = [['immediatePower','即时能力',false],['civilianBenefit','民生收益',false],['resilience','体系韧性',false],['legitimacy','制度认受',false],['resourceCost','资源成本',true],['escalationRisk','升级风险',true]];

const fmt=(v:number,d=1)=>new Intl.NumberFormat('zh-CN',{maximumFractionDigits:d}).format(v); const pct=(v:number,ratio=false)=>`${fmt(ratio?v*100:v)}%`; const clamp=(v:number)=>Math.max(0,Math.min(100,v));
const authorityNames:Record<AuthorityModel,string>={councilRepublic:'协商议会共和国',technocraticDirectorate:'技术行政委员会',centralCommand:'中央战略指挥体制'};
const ethicNames:Record<string,string>={cooperation:'合作',security:'安全',equality:'平等',merit:'能力治理',openness:'开放',continuity:'文明延续'};
const stageNames:Record<string,string>={fragmented:'碎片化世界',contestedOrder:'秩序竞逐',hegemonicSettlement:'霸权性整合',globalUnion:'全球共同体'};
function Meter({value,tone=''}:{value:number;tone?:string}){return <span className={`sc-meter ${tone}`}><i style={{width:`${clamp(value)}%`}}/></span>}
function Card({title,value,detail,tone=''}:{title:string;value:string;detail:string;tone?:string}){return <article className={`sc-stat ${tone}`}><span>{title}</span><strong>{value}</strong><small>{detail}</small></article>}
function Head({kicker,title,detail}:{kicker:string;title:string;detail:string}){return <header className="sc-page-head"><span>{kicker}</span><h2>{title}</h2><p>{detail}</p></header>}
function Empty({title,detail}:{title:string;detail:string}){return <section className="sc-empty"><i>◌</i><h3>{title}</h3><p>{detail}</p><small>此页面已保留独立职责；数据合同尚未接入，不会用其他系统的数字代替。</small></section>}

export function StrategicCabinetApp({onExit}:{onExit:()=>void}):ReactElement{
  const [state,setState]=useState<NationKernelState>(createGlobalUnificationPlaytestState); const [categoryId,setCategoryId]=useState<CategoryId>('nation'); const [tabId,setTabId]=useState('overview'); const [notice,setNotice]=useState('国家战略终端已按独立对象重新组织。选择左侧大类，再在上方切换子页面。');
  const systems=state.civilizationSystems!; const category=categories.find(x=>x.id===categoryId)!; const readiness=globalUnificationReadiness(state)!; const campaign=systems.campaigns['campaign.final-corridor']; const negotiation=systems.negotiations['negotiation.final-order']; const occupation=systems.occupations['occupation.final-bloc']; const settlement=negotiation.settlementId==null?undefined:systems.settlements[negotiation.settlementId];
  const met=Object.values(readiness).filter(x=>x.met).length; const designs=Object.values(state.designs).filter(x=>x.polityId===state.playerPolityId&&x.identity!=null); const lines=Object.values(state.productionLines).filter(x=>x.polityId===state.playerPolityId);
  useEffect(()=>{const old=document.title;document.title='国家战略终端 · Always Game';return()=>{document.title=old}},[]);
  function go(id:CategoryId){const c=categories.find(x=>x.id===id)!;setCategoryId(id);setTabId(c.tabs[0].id)}
  function act(fn:(s:NationKernelState)=>NationKernelState,message:string,rejected='当前条件不足，命令没有生效。'){setState(prev=>{const next=fn(prev);setNotice(next===prev?rejected:message);return next})}
  function advance(days:number){act(s=>advanceNationKernelDays(s,days),`已推进 ${days} 日：所有板块按同一时间线完成结算。`)}
  function serviceRoute(){act(s=>setOccupationApproach(setEconomicAllocation(s,{militaryShare:.21,civilianShare:.28,reconstructionShare:.24,researchShare:.12,logisticsShare:.15}),occupation.id,25,30),'已采用公共服务整合路线，并保留最低守备预算。')}

  function renderPage():ReactElement{
    if(tabId==='direction-options') { const domain=categoryId; const selection=systems.strategicDirections[domain]; const options=Object.values(directionCatalog).filter(option=>option.domain===domain); return <><Head kicker={`${category.label} / 方向对比`} title={`${category.label}的四条对立路线`} detail="四项不是线性升级：它们改变受益者、成本承担者、风险和跨板块后果。选定后90日内不能反复切换。"/><section className="sc-directions">{options.map(option=><article key={option.id} className={selection.selectedOptionId===option.id?'selected':''}><header><span>{option.stance}</span><em>{selection.selectedOptionId===option.id?'当前方向':'候选路线'}</em></header><h3>{option.title}</h3><p>{option.summary}</p><div className="sc-direction-actors"><small><b>主要受益：</b>{option.beneficiary}</small><small><b>主要承担：</b>{option.burdenBearer}</small><small><b>前置条件：</b>{option.prerequisite}</small></div><div className="sc-direction-metrics">{directionMetricLabels.map(([key,label,inverse])=><label key={key}><span>{label}<b>{option.metrics[key]}</b></span><Meter value={option.metrics[key]} tone={inverse&&option.metrics[key]>=70?'danger':!inverse&&option.metrics[key]>=70?'good':''}/></label>)}</div><ul>{option.consequences.map(item=><li key={item}>{item}</li>)}</ul><button disabled={selection.selectedOptionId===option.id||selection.revisionCooldownDays>0} onClick={()=>act(s=>selectStrategicDirection(s,domain,option.id),`“${option.title}”已成为${category.label}板块的试验方向。`,'方向相同，或90日修订冷却尚未结束。')}>{selection.selectedOptionId===option.id?'当前方向':selection.revisionCooldownDays>0?`修订冷却 ${selection.revisionCooldownDays} 日`:'选择此方向'}</button></article>)}</section></> }
    if(tabId==='overview') return <><Head kicker="国家" title="国家总览" detail="这里只显示全局状态、警报与入口，不在总览页直接操作各专业系统。"/><section className="sc-stats"><Card title="政治合法性" value={pct(systems.politics.legitimacy)} detail={`抗议压力 ${fmt(systems.politics.protestPressure)}`} tone="good"/><Card title="经济产出" value={fmt(systems.economy.output)} detail={`债务 ${fmt(systems.economy.debt)}`}/><Card title="民用供应" value={pct(systems.economy.civilianAvailability)} detail={`通胀压力 ${fmt(systems.economy.inflationPressure)}`}/><Card title="全球共同体" value={`${met}/12`} detail={stageNames[systems.globalUnification.stage]} tone="warn"/></section><section className="sc-grid"><article className="sc-panel"><h3>需要处理</h3><button className="sc-row" onClick={()=>go('events')}><span><b>返乡家庭等待政府决定</b><small>社会事件 · 将改变派系、抵抗和债务</small></span><em>处理 →</em></button><button className="sc-row" onClick={()=>go('diplomacy')}><span><b>跨海峡合作项目尚未启动</b><small>国际合作 · 可以替代纯军事整合</small></span><em>处理 →</em></button><button className="sc-row" onClick={()=>go('global')}><span><b>全球统一条件</b><small>{met} 项已达成，{12-met} 项未达成</small></span><em>查看 →</em></button></article><article className="sc-panel"><h3>当前国家方向</h3><div className="sc-identity"><span>权力结构</span><strong>{authorityNames[systems.identity.authority]}</strong><p>{systems.identity.ethics.map(x=>ethicNames[x]).join(' · ')}</p><button onClick={()=>{go('nation');setTimeout(()=>setTabId('identity'),0)}}>进入政体页面</button></div></article></section></>;
    if(tabId==='identity') return <><Head kicker="国家 / 政体" title="选择权力如何组织" detail="政体是长期国家身份。改革会改变合法性、派系态度和执行方式，并有一年冷却期。"/><section className="sc-choice-3">{([['councilRepublic','协商议会共和国','通过地区代表、公共服务与协商形成合法性。'],['technocraticDirectorate','技术行政委员会','由专业机构和工程体系主导决策，执行高效但社会参与较弱。'],['centralCommand','中央战略指挥体制','以统一指挥和紧急权力集中资源，适合危机但会增加政治代价。']] as const).map(([id,title,detail])=><button key={id} className={systems.identity.authority===id?'active':''} onClick={()=>act(s=>setPoliticalIdentity(s,id),`政体改革为“${title}”，相关派系和国家指标已重新结算。`,'政体相同或改革冷却期尚未结束。')}><span>{systems.identity.authority===id?'当前政体':'改革方案'}</span><h3>{title}</h3><p>{detail}</p></button>)}</section><p className="sc-footnote">改革冷却：{systems.identity.reformCooldownDays} 日</p></>;
    if(tabId==='ethics') return <><Head kicker="国家 / 文明理念" title="国家认为什么值得保护" detail="理念决定哪些派系天然认同政府，并为未来政策、事件与外交选择提供条件。"/><section className="sc-ethics">{Object.entries(ethicNames).map(([id,label])=><article className={systems.identity.ethics.includes(id as never)?'active':''} key={id}><i>{systems.identity.ethics.includes(id as never)?'✓':'○'}</i><strong>{label}</strong><small>{systems.identity.ethics.includes(id as never)?'当前核心理念':'当前政体未采用'}</small></article>)}</section></>;
    if(tabId==='domestic'||tabId==='factions') return <><Head kicker="政治 / 派系" title="国内力量不是一个稳定度数字" detail="每个集团拥有影响力、满意度和具体诉求；政策与事件会让支持联盟发生变化。"/><section className="sc-factions">{Object.values(systems.factions).map(f=><article key={f.id}><div><strong>{f.name}</strong><b>{pct(f.satisfaction)}</b></div><Meter value={f.satisfaction} tone={f.satisfaction<45?'danger':'good'}/><p>{f.demand}</p><small>影响力 {fmt(f.influence)} · 倾向理念 {ethicNames[f.alignedEthic]}</small></article>)}</section></>;
    if(tabId==='event-list') return <><Head kicker="事件与局势 / 事件" title="事件必须由世界状态触发，并留下后果" detail="事件不是随机奖励。每个选项会影响具体派系、政治合法性、地区抵抗或国家成本。"/>{Object.values(systems.events).map(e=><article className="sc-event" key={e.id}><span>{e.category} · 第 {e.triggeredDay} 日</span><h3>{e.title}</h3><p>{e.summary}</p>{e.status==='active'?<div>{e.optionIds.map(id=>{const o=systems.eventOptions[id];return <button key={id} onClick={()=>act(s=>resolveStrategicEvent(s,e.id,id),`已选择“${o.title}”，政治与社会后果已写入国家状态。`)}><strong>{o.title}</strong><small>{o.summary}</small></button>})}</div>:<em>已选择：{systems.eventOptions[e.resolvedOptionId!]?.title}</em>}</article>)}</>;
    if(tabId==='situations') return <><Head kicker="事件与局势 / 局势" title="持续问题会在时间中发展" detail="投入、政策和社会条件影响局势进度；忽视问题也会产生压力。"/><section className="sc-grid">{Object.values(systems.situations).map(s=><article className="sc-panel padded" key={s.id}><span>{s.status}</span><h3>{s.title}</h3><p>{s.summary}</p><label>制度过渡进度 <b>{pct(s.progress)}</b></label><Meter value={s.progress} tone="good"/><label>局势压力 <b>{pct(s.pressure)}</b></label><Meter value={s.pressure} tone="danger"/><button onClick={()=>advance(30)}>观察一个月</button></article>)}</section></>;
    if(tabId==='technology'||tabId==='current'||tabId==='tech-archive') { const all=Object.values(systems.technologies); const shown=tabId==='current'?all.filter(x=>x.status==='researching'):tabId==='tech-archive'?all.filter(x=>x.status==='completed'):all; return <><Head kicker="科研" title={tabId==='current'?'当前研究':tabId==='tech-archive'?'科技档案':'全球统一阶段科技树'} detail="首批节点直接来自TIMELINE 240—580年及全球统一扩展；研究完成会解锁工程并改变对应系统。"/><section className="sc-tech-list">{shown.length===0?<Empty title="当前没有进行中的研究" detail="在科技树中选择一个可研究节点。"/>:shown.map(t=><article className={`status-${t.status}`} key={t.id}><div><span>{t.domain} · {t.timelineYears}</span><em>{t.status==='completed'?'已完成':t.status==='researching'?'研究中':t.status==='available'?'可研究':'前置未满足'}</em></div><h3>{t.title}</h3><p>{t.summary}</p><small>失败与代价：{t.failureCost}</small><Meter value={t.progress/t.workRequired*100} tone={t.status==='completed'?'good':t.status==='locked'?'':'warn'}/><footer><span>{fmt(t.progress)} / {fmt(t.workRequired)}</span><button disabled={t.status!=='available'} onClick={()=>act(s=>startCivilizationTechnology(s,t.id),`已开始研究“${t.title}”。`,'需要先完成前置科技，或已有另一项研究正在进行。')}>{t.status==='completed'?'已归档':t.status==='researching'?'研究进行中':t.status==='locked'?'前置未满足':'开始研究'}</button></footer></article>)}</section></> }
    if(tabId==='policies') return <><Head kicker="政治 / 政策与法令" title="时间线政策试运行" detail="政策是有期限的国家行动，会持续产生代价，并在结束时留下政治和制度结果。"/><section className="sc-policy-list">{Object.values(systems.policies).map(p=><article key={p.id} className={p.status}><div><span>{p.category}</span><em>{p.status==='active'?`剩余 ${p.remainingDays} 日`:p.status==='cooldown'?`冷却 ${p.remainingDays} 日`:'可启动'}</em></div><h3>{p.title}</h3><p>{p.summary}</p><small>执行期 {p.durationDays} 日 · 冷却期 {p.cooldownDays} 日</small><button disabled={p.status!=='available'} onClick={()=>act(s=>activateCivilizationPolicy(s,p.id),`政策“${p.title}”已经生效，将按日产生政治、社会或经济后果。`)}>{p.status==='active'?'执行中':p.status==='cooldown'?'冷却中':'启动政策'}</button></article>)}</section></>;
    if(tabId==='projects'||tabId==='queue') { const all=Object.values(systems.developmentProjects); const shown=tabId==='queue'?all.filter(x=>x.status==='building'):all; return <><Head kicker="建设" title={tabId==='queue'?'建设队列':'全球统一阶段国家工程'} detail="科技只形成能力；国家工程必须继续投入重建预算，完工后才形成基础设施和制度结果。"/><section className="sc-projects">{shown.length===0?<Empty title="建设队列为空" detail="进入国家工程页面，选择已经满足科技前置的工程。"/>:shown.map(p=><article key={p.id}><span>{p.category} · {p.status}</span><h3>{p.title}</h3><p>{p.summary}</p><Meter value={p.progress/p.workRequired*100} tone={p.status==='completed'?'good':'warn'}/><small>工程进度 {fmt(p.progress)} / {fmt(p.workRequired)} · 前置科技 {p.requiredTechnologyIds.length} 项</small><div><button disabled={p.status!=='available'} onClick={()=>act(s=>startNationalDevelopmentProject(s,p.id),`国家工程“${p.title}”已经开工。`,'需要先完成对应科技，或工程已经启动。')}>{p.status==='completed'?'已竣工':p.status==='building'?'建设中':p.status==='locked'?'科技未解锁':'开工建设'}</button></div></article>)}</section></> }
    if(tabId==='budget'||tabId==='economic-overview'||tabId==='finance') return <><Head kicker="经济" title={tabId==='budget'?'国家预算':'经济与财政'} detail="政府预算与社会经济分开呈现；预算是操作，经济和财政是结果。"/><section className="sc-stats"><Card title="总产出" value={fmt(systems.economy.output)} detail={`财政收入 ${fmt(systems.economy.revenue)}`}/><Card title="国家债务" value={fmt(systems.economy.debt)} detail={`债务率 ${fmt(systems.economy.debt/systems.economy.output,2)}`}/><Card title="民用供应" value={pct(systems.economy.civilianAvailability)} detail={`通胀 ${fmt(systems.economy.inflationPressure)}`}/><Card title="维修资金" value={fmt(systems.economy.repairFunding)} detail="基础设施与设备维护"/></section>{tabId==='budget'&&<section className="sc-choice-3"><button onClick={serviceRoute}><h3>民生与重建</h3><p>军事21% · 民生28% · 重建24% · 科研12% · 物流15%</p></button><button onClick={()=>act(s=>setEconomicAllocation(s,{militaryShare:.46,civilianShare:.15,reconstructionShare:.07,researchShare:.1,logisticsShare:.22}),'已切换为紧急军事预算。')}><h3>紧急军事预算</h3><p>军事46% · 民生15% · 重建7% · 科研10% · 物流22%</p></button></section>}</>;
    if(tabId==='military-industry') return <><Head kicker="工业 / 军事工业" title="生产线只管理制造" detail="装备性能、库存和部队交付分别在装备与陆军页面查看。"/><section className="sc-grid">{lines.map(line=>{const d=state.designs[line.designId],stock=state.stockpiles[line.stockpileId],p=d.identity?strategicAssetPresentation(d.identity.presentationId):undefined;return <article className="sc-panel padded" key={line.id}><span>装备生产栏</span><h3>{p?.displayName??d.id}</h3><div className="sc-factories"><small>投入军工厂</small><button onClick={()=>act(s=>assignProductionFactories(s,line.id,(line.assignedFactoryUnits??0)-1),'已减少一座军工厂。')}>−</button><b>{line.assignedFactoryUnits??0}</b><button onClick={()=>act(s=>assignProductionFactories(s,line.id,(line.assignedFactoryUnits??0)+1),'已增加一座军工厂。')}>＋</button></div><label>生产效率 <b>{pct(line.efficiency,true)}</b></label><Meter value={line.efficiency*100}/><label>日产量 <b>{fmt(line.dailyOutput)}</b></label><Meter value={line.dailyOutput*15} tone="good"/><small>当前库存只作交叉提示：{fmt(stock?.quantity??0)}；完整库存操作在“装备 → 库存”。</small></article>})}</section></>;
    if(tabId==='industrial-route') return <><Head kicker="工业 / 工业路线" title="工业体系如何换取峰值或韧性" detail="路线修正生产链，不直接生成装备。"/><section className="sc-choice-3"><button onClick={()=>{const x=createIndustrialStrategy('policy.industry.limited-mobilization','technology-route.industry.flexible');if(x)act(s=>setIndustrialStrategy(s,x),'已采用弹性生产线。')}}><h3>弹性生产线</h3><p>换型更快、效率保留更高、受损恢复更好。</p></button><button onClick={()=>{const x=createIndustrialStrategy('policy.industry.limited-mobilization','technology-route.industry.concentrated');if(x)act(s=>setIndustrialStrategy(s,x),'已采用集中工业。')}}><h3>集中工业</h3><p>成熟产线峰值更高，但换型和受损代价更大。</p></button></section></>;
    if(['design','catalog','strategic-assets'].includes(tabId)) return <><Head kicker="装备" title={tabId==='strategic-assets'?'战略资产':'装备设计与目录'} detail="型号身份、威力、限制与服役意义独立于工厂生产操作。"/><section className="sc-assets">{designs.map(d=>{const p=strategicAssetPresentation(d.identity!.presentationId)!;return <article key={d.id}><span>{d.kind}</span><h3>{p.displayName}</h3><p>{p.impactSummary}</p><div><b>拥有它意味着</b>{p.civilizationMeaning}</div><small>{p.limitationSummary}</small></article>})}</section></>;
    if(tabId==='stockpile'||tabId==='equipment-maintenance') return <><Head kicker="装备" title={tabId==='stockpile'?'装备库存':'装备维护'} detail="库存回答拥有多少；维护回答其中多少能够可靠服役。"/><section className="sc-table">{Object.values(state.stockpiles).filter(x=>x.polityId===state.playerPolityId).map(x=><div key={x.id}><strong>{x.designId?state.designs[x.designId]?.identity?strategicAssetPresentation(state.designs[x.designId].identity!.presentationId)?.displayName:x.designId:x.kind}</strong><span>库存 {fmt(x.quantity)}</span><span>预留 {fmt(x.reserved)}</span><span>状态 {pct(x.condition??100)}</span></div>)}</section></>;
    if(tabId==='logistics-overview'||tabId==='shipping'||tabId==='airlift') return <><Head kicker="物流" title={tabId==='shipping'?'海运':tabId==='airlift'?'空运':'物流总览'} detail="物流只管理运输能力和瓶颈；海军与空军作战分别在军种页面。"/><section className="sc-stats"><Card title="有效运力" value={fmt(systems.logistics.effectiveCapacity)} detail={`缺口 ${fmt(systems.logistics.bottleneck)}`}/><Card title="海运吞吐" value={fmt(systems.logistics.maritimeThroughput)} detail={`航路安全 ${pct(systems.maritime.routeSecurity)}`}/><Card title="空运能力" value={fmt(systems.logistics.airliftCapacity)} detail={`${fmt(systems.aerospace.transportAircraft,0)} 架运输机`}/><Card title="网络冗余" value={pct(systems.logistics.redundancy)} detail={`中断 ${fmt(systems.logistics.disruption)}`}/></section></>;
    if(['administration','services','integration','occupation','reconstruction','region-overview'].includes(tabId)) return <><Head kicker="地区" title={tabId==='occupation'?'占领管理':tabId==='integration'?'地区整合':tabId==='services'?'公共服务':tabId==='administration'?'地方行政':tabId==='reconstruction'?'战后重建':'地区总览'} detail="军事控制、行政执行、公共服务、重建和长期整合分别呈现。"/><section className="sc-stats"><Card title="安全" value={pct(occupation.security)} detail="占领管理"/><Card title="人口登记" value={pct(occupation.registry)} detail="地方行政"/><Card title="公共服务" value={pct(occupation.services)} detail="居民日常生活"/><Card title="司法" value={pct(occupation.justice)} detail="制度执行"/><Card title="居民信任" value={pct(occupation.civilianTrust)} detail="长期整合"/><Card title="抵抗" value={pct(occupation.resistance)} detail={`${fmt(occupation.displacedPopulation,0)} 人流离`} tone="danger"/></section><div className="sc-actions"><button className="primary" onClick={serviceRoute}>采用公共服务整合</button><button onClick={()=>advance(90)}>运行90日</button></div></>;
    if(tabId==='negotiation') return <><Head kicker="外交 / 谈判" title="最后秩序谈判" detail="具体议题、要求和筹码独立于长期外交关系。"/><section className="sc-stats"><Card title="接受度" value={pct(negotiation.acceptance)} detail={negotiation.status}/><Card title="可信度" value={fmt(negotiation.credibility)} detail="长期履约记录"/><Card title="军事筹码" value={fmt(negotiation.militaryLeverage)} detail="不能替代合法性"/><Card title="让步价值" value={fmt(negotiation.concessionValue)} detail="协议交换"/></section><div className="sc-actions"><button onClick={()=>advance(1)}>推进一轮谈判</button><button onClick={()=>act(s=>conductMissileDemonstration(s,negotiation.id),'导弹展示提高筹码，同时增加紧张与怨恨。')}>展示战略武力</button></div></>;
    if(['alliances','cooperation','international-orgs','space-cooperation','public-projects'].includes(tabId)) return <><Head kicker="外交 / 国际合作" title="跨海峡重建与通信共同体" detail="合作不是谈判附属品：组织拥有成员、规则、合法性、共同预算和长期项目。"/><section className="sc-stats">{Object.values(systems.organizations).map(o=><><Card key={`${o.id}.cohesion`} title="组织凝聚力" value={pct(o.cohesion)} detail={`${o.memberPolityIds.length} 个成员 · 共识规则`}/><Card key={`${o.id}.legitimacy`} title="组织合法性" value={pct(o.legitimacy)} detail={`共同预算 ${fmt(o.commonBudget)}`}/></>)}</section><section className="sc-projects">{Object.values(systems.cooperationProjects).map(p=><article key={p.id}><span>{p.kind} · {p.status}</span><h3>{p.title}</h3><Meter value={p.progress/p.requiredProgress*100} tone="good"/><small>进度 {fmt(p.progress)} / {fmt(p.requiredProgress)} · 我方投入 {fmt(p.contribution)} · 伙伴投入 {fmt(p.partnerContribution)}</small><div><button disabled={p.status!=='proposed'} onClick={()=>act(s=>startCooperationProject(s,p.id),`合作项目“${p.title}”已经启动。`)}>启动项目</button><button disabled={p.status==='completed'} onClick={()=>act(s=>setCooperationContribution(s,p.id,p.contribution+5),'已提高我国项目投入。')}>追加投入</button></div></article>)}</section></>;
    if(tabId==='satellites'||tabId==='space-program'||tabId==='launches'||tabId==='ground-stations') return <><Head kicker="航天" title={tabId==='satellites'?'卫星网络':tabId==='launches'?'发射任务':tabId==='ground-stations'?'地面站':'航天计划'} detail="航天计划、发射任务、在轨卫星和地面保障是同一大类下的独立子页面。"/><section className="sc-stats"><Card title="轨道覆盖" value={pct(systems.satellites.orbitalCoverage)} detail={`可靠度 ${pct(systems.satellites.reliability)}`}/><Card title="通信卫星" value={`${systems.satellites.communicationSatellites} 颗`} detail="全球通信与协调"/><Card title="侦察卫星" value={`${systems.satellites.reconnaissanceSatellites} 颗`} detail="情报与战区感知"/><Card title="地面站容量" value={fmt(systems.satellites.groundStationCapacity)} detail={`剩余发射能力 ${fmt(systems.satellites.launchCapacity)}`}/></section><div className="sc-actions"><button onClick={()=>act(s=>launchBasicSatellite(s,'communication'),'通信卫星发射完成。')}>发射通信卫星</button><button onClick={()=>act(s=>launchBasicSatellite(s,'weather'),'气象卫星发射完成。')}>发射气象卫星</button></div></>;
    if(tabId==='campaigns'||tabId==='theatres'||tabId==='war-overview'||tabId==='losses') return <><Head kicker="战争" title={tabId==='campaigns'?'海峡走廊战役':tabId==='theatres'?'海峡战区':tabId==='losses'?'伤亡与损失':'战争总览'} detail="战争目标、战区范围、具体战役和损失分别管理。"/><section className="sc-stats"><Card title="战场控制" value={pct(campaign.control)} detail={campaign.status}/><Card title="我方疲劳" value={pct(campaign.attackerExhaustion)} detail={`持续 ${campaign.elapsedDays} 日`}/><Card title="人员损失" value={fmt(campaign.attackerPersonnelLosses,0)} detail="我方累计" tone="danger"/><Card title="民用影响" value={fmt(campaign.civilianImpact)} detail={`设施损害 ${fmt(campaign.infrastructureDamage)}`} tone="danger"/></section><div className="sc-actions"><button onClick={()=>advance(10)}>继续行动10日</button><button onClick={()=>{setCategoryId('diplomacy');setTabId('negotiation')}}>转入谈判</button></div></>;
    if(tabId==='unification'||tabId==='world-order'||tabId==='institutions') return <><Head kicker="全球共同体" title={tabId==='unification'?'全球统一进程':tabId==='institutions'?'共同机构':'全球秩序'} detail="这里只呈现全球制度和统一条件；具体短板必须返回相应专业页面解决。"/><section className="sc-gates">{Object.entries(readiness).map(([id,x])=><article className={x.met?'met':''} key={id}><i>{x.met?'✓':'!'}</i><span><strong>{id}</strong><small>{fmt(x.current,2)} / {fmt(x.required,2)}</small><Meter value={(id==='resistancePressure'||id==='fiscalSustainability'||id==='independentBlocs')?x.required/Math.max(x.required,x.current)*100:x.current/Math.max(.001,x.required)*100} tone={x.met?'good':'warn'}/></span></article>)}</section><div className="sc-actions"><button disabled={settlement?.status!=='active'} onClick={()=>settlement&&act(s=>ratifyGlobalSettlement(s,settlement.id),'全球协议已批准。')}>批准共同制度</button><button onClick={()=>advance(180)}>运行制度180日</button></div></>;
    const pageLabel=category.tabs.find(x=>x.id===tabId)?.label??category.label; const objects=boardCatalog[categoryId];
    return <><Head kicker={`${category.label} / ${pageLabel}`} title={`${pageLabel} · 首批运行对象`} detail="本页先接入该板块的四个核心对象，用容量、准备度、压力、输入、产出与下一行动验证信息结构；后续再替换为各自的完整运行合同。"/><section className="sc-board-objects">{objects.map(object=><article key={object.id} className={object.status}><header><span>{object.kind}</span><em>{object.status==='stable'?'稳定':object.status==='developing'?'推进中':object.status==='strained'?'承压':'受阻'}</em></header><h3>{object.title}</h3><p>{object.summary}</p><div className="sc-object-metrics"><label>容量 <b>{object.capacity}</b><Meter value={object.capacity}/></label><label>准备度 <b>{object.readiness}</b><Meter value={object.readiness} tone={object.readiness>=70?'good':'warn'}/></label><label>压力 <b>{object.pressure}</b><Meter value={object.pressure} tone={object.pressure>=60?'danger':''}/></label></div><dl><div><dt>需要</dt><dd>{object.input}</dd></div><div><dt>形成</dt><dd>{object.output}</dd></div></dl><button onClick={()=>setNotice(`${object.title}：下一行动是“${object.nextAction}”。当前为内容与数据结构试验，尚未写入自动结算。`)}>下一行动：{object.nextAction}</button></article>)}</section></>;
  }

  return <main className="sc-shell"><aside className="sc-sidebar"><div className="sc-brand"><b>AG</b><span><strong>ALWAYS GAME</strong><small>国家战略终端</small></span></div><nav>{categories.map(c=><button key={c.id} className={categoryId===c.id?'active':''} onClick={()=>go(c.id)}><i>{c.icon}</i><span>{c.label}</span>{c.id==='events'&&Object.values(systems.events).some(e=>e.status==='active')&&<em>1</em>}</button>)}</nav></aside><section className="sc-work"><header className="sc-top"><div><small>{category.label}</small><strong>{category.tabs.find(x=>x.id===tabId)?.label}</strong></div><div className="sc-date"><small>余烬历 {state.calendar.year}年{state.calendar.month}月</small><strong>第 {state.calendar.day} 日</strong></div><div><button onClick={()=>advance(1)}>+1日</button><button onClick={()=>advance(10)}>+10日</button><button className="primary" onClick={()=>advance(30)}>推进一月</button><button onClick={()=>{setState(createGlobalUnificationPlaytestState());setNotice('场景已重置。')}}>重置</button><button onClick={onExit}>退出</button></div></header><div className="sc-tabs">{category.tabs.map(t=><button className={tabId===t.id?'active':''} key={t.id} onClick={()=>setTabId(t.id)}>{t.label}</button>)}</div><div className="sc-notice"><b>调度简报</b><span>{notice}</span></div><div className="sc-content">{renderPage()}</div></section></main>;
}
