import { advanceNationKernelDays, conductMissileDemonstration, createCampaign, createDiplomaticIssue, createNegotiation, launchBasicSatellite, validateNationKernel } from '../src/v2/nationKernel';
import { createCivilizationTestState } from './civilization-sim-fixture';
import type { CampaignState, NationKernelState } from '../src/v2/nationKernel/types';

function assert(value: unknown, message: string): asserts value { if (!value) throw new Error(message); }
const makeCampaign = (id: string): CampaignState => ({ id, theatreId: 'theatre.border-sea', attackerPolityId: 'polity.player', defenderPolityId: 'polity.neighbor', attackerFormationIds: ['formation.r28b.border-guard', 'formation.r29a.mobile-reserve'], defenderFormationIds: ['formation.test.peer-field'], objective: 'limitedAdvance', status: 'active', dayStarted: 0, elapsedDays: 0, supplyDemand: 44, intelligence: 45, attackerPressure: 50, defenderDepth: 58, control: 50, attackerExhaustion: 0, defenderExhaustion: 0, attackerPersonnelLosses: 0, defenderPersonnelLosses: 0, equipmentLosses: 0, civilianImpact: 4, infrastructureDamage: 2, stopAtExhaustion: 72 });

const base = createCivilizationTestState();
const blockedShipping = structuredClone(base) as NationKernelState; blockedShipping.civilizationSystems!.maritime.blockadePressure = 70; blockedShipping.civilizationSystems!.maritime.escortCapacity = 2; blockedShipping.civilizationSystems!.maritime.routeSecurity = 35;
const escortedShipping = structuredClone(base) as NationKernelState; escortedShipping.civilizationSystems!.maritime.blockadePressure = 70; escortedShipping.civilizationSystems!.maritime.escortCapacity = 34; escortedShipping.civilizationSystems!.maritime.routeSecurity = 35; escortedShipping.civilizationSystems!.maritime.navalReadiness = 78;
const blockedAfter = advanceNationKernelDays(blockedShipping, 30); const escortedAfter = advanceNationKernelDays(escortedShipping, 30);
assert(escortedAfter.civilizationSystems!.maritime.convoyLossRate < blockedAfter.civilizationSystems!.maritime.convoyLossRate && escortedAfter.civilizationSystems!.logistics.maritimeThroughput > blockedAfter.civilizationSystems!.logistics.maritimeThroughput, 'escort and naval readiness did not preserve shipping under blockade');

const lowFuel = structuredClone(base) as NationKernelState; lowFuel.civilizationSystems!.aerospace.fuelAvailability = 18; lowFuel.civilizationSystems!.aerospace.aircraftReadiness = 55;
const supportedAir = structuredClone(base) as NationKernelState; supportedAir.civilizationSystems!.aerospace.fuelAvailability = 90; supportedAir.civilizationSystems!.aerospace.aircraftReadiness = 82; supportedAir.civilizationSystems!.aerospace.combatAircraft = 64; supportedAir.civilizationSystems!.aerospace.transportAircraft = 18;
const lowFuelAfter = advanceNationKernelDays(lowFuel, 30); const supportedAirAfter = advanceNationKernelDays(supportedAir, 30);
assert(supportedAirAfter.civilizationSystems!.aerospace.airSuperiority > lowFuelAfter.civilizationSystems!.aerospace.airSuperiority && supportedAirAfter.civilizationSystems!.logistics.airliftCapacity > lowFuelAfter.civilizationSystems!.logistics.airliftCapacity, 'aircraft count produced capability without readiness and fuel');

const launchReady = structuredClone(base) as NationKernelState; launchReady.civilizationSystems!.satellites.launchCapacity = 2; launchReady.civilizationSystems!.satellites.reliability = 82; launchReady.civilizationSystems!.satellites.launchFailureRisk = 18;
const launchFailed = structuredClone(base) as NationKernelState; launchFailed.civilizationSystems!.satellites.launchCapacity = 2; launchFailed.civilizationSystems!.satellites.reliability = 22; launchFailed.civilizationSystems!.satellites.launchFailureRisk = 65;
const launched = launchBasicSatellite(launchReady, 'communication'); const failed = launchBasicSatellite(launchFailed, 'communication');
assert(launched.civilizationSystems!.satellites.communicationSatellites === launchReady.civilizationSystems!.satellites.communicationSatellites + 1, 'reliable launch did not place a basic satellite');
assert(failed.civilizationSystems!.satellites.communicationSatellites === launchFailed.civilizationSystems!.satellites.communicationSatellites && failed.civilizationSystems!.satellites.launchCapacity === launchFailed.civilizationSystems!.satellites.launchCapacity - 1, 'failed launch did not consume capacity without granting a satellite');

const groundOnlyBase = structuredClone(base) as NationKernelState; Object.assign(groundOnlyBase.civilizationSystems!.maritime, { merchantShipping: 0, escortCapacity: 0, portCapacity: 0, routeSecurity: 0 }); Object.assign(groundOnlyBase.civilizationSystems!.aerospace, { combatAircraft: 0, transportAircraft: 0, aircraftReadiness: 0, airSuperiority: 0, fuelAvailability: 0 }); Object.assign(groundOnlyBase.civilizationSystems!.satellites, { reconnaissanceSatellites: 0, communicationSatellites: 0, weatherSatellites: 0, orbitalCoverage: 0 }); groundOnlyBase.civilizationSystems!.logistics.freightCapacity = 45; groundOnlyBase.civilizationSystems!.logistics.disruption = 22;
const fullStackBase = structuredClone(base) as NationKernelState; fullStackBase.civilizationSystems!.logistics.freightCapacity = 45; fullStackBase.civilizationSystems!.logistics.disruption = 22; Object.assign(fullStackBase.civilizationSystems!.maritime, { merchantShipping: 55, escortCapacity: 28, portCapacity: 48, routeSecurity: 78, navalReadiness: 76 }); Object.assign(fullStackBase.civilizationSystems!.aerospace, { combatAircraft: 64, transportAircraft: 18, aircraftReadiness: 82, airSuperiority: 28, fuelAvailability: 90 }); Object.assign(fullStackBase.civilizationSystems!.satellites, { reconnaissanceSatellites: 2, communicationSatellites: 2, weatherSatellites: 1, orbitalCoverage: 45, reliability: 84, groundStationCapacity: 72 });
let groundOnly = createCampaign(groundOnlyBase, makeCampaign('campaign.ground-only')); let fullStack = createCampaign(fullStackBase, makeCampaign('campaign.full-stack')); groundOnly = advanceNationKernelDays(groundOnly, 30); fullStack = advanceNationKernelDays(fullStack, 30);
assert(fullStack.civilizationSystems!.campaigns['campaign.full-stack'].control > groundOnly.civilizationSystems!.campaigns['campaign.ground-only'].control && fullStack.civilizationSystems!.campaigns['campaign.full-stack'].attackerExhaustion < groundOnly.civilizationSystems!.campaigns['campaign.ground-only'].attackerExhaustion, 'maritime, air and satellite support did not change campaign outcome and endurance');

let missile = createDiplomaticIssue(base, { id: 'issue.missile-test', actorIds: ['polity.player', 'polity.neighbor'], kind: 'security', importance: 65, tension: 45, grievance: 35, status: 'open' }); missile = createNegotiation(missile, { id: 'negotiation.missile-test', issueId: 'issue.missile-test', proposerId: 'polity.player', counterpartId: 'polity.neighbor', demandLevel: 45, concessionValue: 20, militaryLeverage: 15, economicPressure: 10, credibility: 45, acceptance: 0, status: 'active' }); const beforeTension = missile.civilizationSystems!.diplomaticIssues['issue.missile-test'].tension; missile = conductMissileDemonstration(missile, 'negotiation.missile-test');
assert(missile.civilizationSystems!.negotiations['negotiation.missile-test'].credibility > 45 && missile.civilizationSystems!.diplomaticIssues['issue.missile-test'].tension > beforeTension, 'missile demonstration did not increase both credibility and escalation tension');
for (const state of [blockedAfter, escortedAfter, lowFuelAfter, supportedAirAfter, launched, failed, groundOnly, fullStack, missile]) { const validation = validateNationKernel(state); assert(validation.ok, validation.errors.join(', ')); }

console.log(JSON.stringify({ ok: true, maritime30Days: { blocked: blockedAfter.civilizationSystems!.maritime, escorted: escortedAfter.civilizationSystems!.maritime }, aviation30Days: { lowFuel: lowFuelAfter.civilizationSystems!.aerospace, supported: supportedAirAfter.civilizationSystems!.aerospace }, satelliteLaunch: { successCount: launched.civilizationSystems!.satellites.communicationSatellites, failedCount: failed.civilizationSystems!.satellites.communicationSatellites }, campaign30Days: { groundOnly: groundOnly.civilizationSystems!.campaigns['campaign.ground-only'], fullStack: fullStack.civilizationSystems!.campaigns['campaign.full-stack'] }, missileDemonstration: { credibility: missile.civilizationSystems!.negotiations['negotiation.missile-test'].credibility, tension: missile.civilizationSystems!.diplomaticIssues['issue.missile-test'].tension } }, null, 2));
