import { advanceNationKernelDays, createDiplomaticIssue, createNegotiation, createOccupation, globalUnificationReadiness, ratifyGlobalSettlement, setEconomicAllocation, setOccupationApproach, validateNationKernel } from '../src/v2/nationKernel';
import { createCivilizationTestState } from './civilization-sim-fixture';
import type { NationKernelState, OccupationState } from '../src/v2/nationKernel/types';

function assert(value: unknown, message: string): asserts value { if (!value) throw new Error(message); }
const occupation: OccupationState = { id: 'occupation.final-bloc', polityId: 'polity.player', regionId: 'region.neighbor', security: 32, resistance: 58, registry: 12, services: 15, justice: 8, localCooperation: 18, fiscalIntegration: 0, reconstruction: 8, garrisonDemand: 20, serviceDemand: 26, coercion: 35, civilianTrust: 20, displacedPopulation: 18_000, dailyCost: 0, status: 'militaryControl' };

const seed = createCivilizationTestState();
Object.assign(seed.civilizationSystems!.globalUnification, { independentBlocs: 2, controlledTerritoryRatio: 0.78, integratedPopulationRatio: 0.72, commonInstitutionScore: 56, externalRecognition: 58, resistancePressure: 38, sharedInfrastructure: 48, stage: 'contestedOrder' });

let coercive = createOccupation(seed, occupation); coercive = setOccupationApproach(coercive, 'occupation.final-bloc', 88, 8); coercive = setEconomicAllocation(coercive, { militaryShare: 0.48, civilianShare: 0.14, reconstructionShare: 0.06, researchShare: 0.1, logisticsShare: 0.22 }); Object.assign(coercive.civilizationSystems!.politics, { emergencyPower: 82, legitimacy: 62, regionalCompliance: 58 }); Object.assign(coercive.civilizationSystems!.aerospace, { strategicStrikeRisk: 45, missileStockpile: 70 });
coercive.civilizationSystems!.globalUnification.controlledTerritoryRatio = 0.91; coercive = advanceNationKernelDays(coercive, 720);

let cooperative = createOccupation(seed, occupation); cooperative = setOccupationApproach(cooperative, 'occupation.final-bloc', 25, 30); cooperative = setEconomicAllocation(cooperative, { militaryShare: 0.2, civilianShare: 0.29, reconstructionShare: 0.24, researchShare: 0.12, logisticsShare: 0.15 }); Object.assign(cooperative.civilizationSystems!.politics, { emergencyPower: 10, legitimacy: 70, regionalCompliance: 72 }); Object.assign(cooperative.civilizationSystems!.logistics, { redundancy: 78, freightCapacity: 82, disruption: 5 }); Object.assign(cooperative.civilizationSystems!.maritime, { merchantShipping: 62, escortCapacity: 30, portCapacity: 55, routeSecurity: 82, navalReadiness: 78 }); Object.assign(cooperative.civilizationSystems!.aerospace, { combatAircraft: 52, transportAircraft: 20, aircraftReadiness: 80, fuelAvailability: 84, airSuperiority: 35 }); Object.assign(cooperative.civilizationSystems!.satellites, { reconnaissanceSatellites: 2, communicationSatellites: 3, weatherSatellites: 2, reliability: 86, orbitalCoverage: 55, groundStationCapacity: 80 });
cooperative = createDiplomaticIssue(cooperative, { id: 'issue.final-order', actorIds: ['polity.player', 'polity.neighbor'], kind: 'security', importance: 65, tension: 55, grievance: 45, status: 'open' }); cooperative = createNegotiation(cooperative, { id: 'negotiation.final-order', issueId: 'issue.final-order', proposerId: 'polity.player', counterpartId: 'polity.neighbor', demandLevel: 22, concessionValue: 42, militaryLeverage: 22, economicPressure: 15, credibility: 84, acceptance: 0, status: 'active' }); cooperative = advanceNationKernelDays(cooperative, 5);
const settlementId = cooperative.civilizationSystems!.negotiations['negotiation.final-order'].settlementId; assert(settlementId != null, 'cooperative global settlement was not negotiated'); cooperative = ratifyGlobalSettlement(cooperative, settlementId); cooperative = advanceNationKernelDays(cooperative, 720);

const coerciveGlobal = coercive.civilizationSystems!.globalUnification; const cooperativeGlobal = cooperative.civilizationSystems!.globalUnification; const coerciveOccupation = coercive.civilizationSystems!.occupations['occupation.final-bloc']; const cooperativeOccupation = cooperative.civilizationSystems!.occupations['occupation.final-bloc'];
assert(coerciveGlobal.stage !== 'globalUnion', 'territorial control alone incorrectly completed global unification');
assert(coerciveOccupation.fiscalIntegration === 0 && coerciveGlobal.resistancePressure > cooperativeGlobal.resistancePressure, 'coercive conquest avoided governance and resistance costs');
assert(cooperativeOccupation.status === 'integrated', 'cooperative service and institution route did not integrate the final region');
assert(cooperativeGlobal.stage === 'globalUnion', 'multi-system cooperative route did not reach global union after meeting all gates');
const readiness = globalUnificationReadiness(cooperative); assert(readiness != null && Object.values(readiness).every((item) => item.met), 'global union status bypassed a readiness gate');
const withoutSpace = structuredClone(cooperative) as NationKernelState; withoutSpace.civilizationSystems!.globalUnification.stage = 'hegemonicSettlement'; withoutSpace.civilizationSystems!.globalUnification.sharedInfrastructure = 50; withoutSpace.civilizationSystems!.satellites.communicationSatellites = 0; withoutSpace.civilizationSystems!.satellites.orbitalCoverage = 0; const incomplete = globalUnificationReadiness(withoutSpace); assert(incomplete != null && !incomplete.sharedInfrastructure.met, 'global framework ignored shared infrastructure and communications gate');
for (const state of [coercive, cooperative, withoutSpace]) { const validation = validateNationKernel(state); assert(validation.ok, validation.errors.join(', ')); }

console.log(JSON.stringify({ ok: true, coercive720Days: { global: coerciveGlobal, occupation: coerciveOccupation, politics: coercive.civilizationSystems!.politics, economy: coercive.civilizationSystems!.economy }, cooperative720Days: { global: cooperativeGlobal, occupation: cooperativeOccupation, politics: cooperative.civilizationSystems!.politics, economy: cooperative.civilizationSystems!.economy, readiness }, missingSharedInfrastructureGate: incomplete?.sharedInfrastructure }, null, 2));
